steps:
- name: gcr.io/cloud-builders/gsutil
  args:
      ['cp', 'gs://demo-app-environments/backend/demo-app/*', '.']
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        sh docker_tag.sh
- name: gcr.io/cloud-builders/docker
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        (docker build --no-cache -t gcr.io/${PROJECT_ID}/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')" -t commit_hash:$COMMIT_SHA .)
- name: gcr.io/cloud-builders/docker
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        (docker push gcr.io/${PROJECT_ID}/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')")
- name: gcr.io/cloud-builders/gsutil
  args:
      [
        'cp',
        'tag_version.txt',
        'gs://demo-app-environments/backend/demo-app/tag_version.txt',
      ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        (gcloud run deploy delfos-app --region=us-central1 --image=gcr.io/${PROJECT_ID}/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')")
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 3600s
