steps:
- name: gcr.io/cloud-builders/gsutil
  args:
      ['cp', 'gs://demo-app-environments/backend/demo-app/*', '.']
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        sh docker_tag.sh
- name: gcr.io/cloud-builders/docker
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        (docker build --no-cache -t gcr.io/${PROJECT_ID}/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')" -t gcr.io/${PROJECT_ID}/demo-app:$COMMIT_SHA -t gcr.io/${PROJECT_ID}/demo-app:$BRANCH_NAME .)
- name: gcr.io/cloud-builders/docker
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        (docker push -a gcr.io/${PROJECT_ID}/demo-app)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        (gcloud run deploy delfos-app --region=us-central1 --image=gcr.io/${PROJECT_ID}/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')") \
        || (echo "Error deploying. Rollbacking...")
        || (gcloud container images delete gcr.io/data-test-skydropx/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')" --force-delete-tags) \
        || (sh tag_rollback.sh) \
        || (gcloud run deploy delfos-app --region=us-central1 --image=gcr.io/${PROJECT_ID}/demo-app:"$(cat tag_version.txt | awk '{n=split($4,A,"="); print A[2];}')") && exit -1
- name: gcr.io/cloud-builders/gsutil
  args:
      [
        'cp',
        'tag_version.txt',
        'gs://demo-app-environments/backend/demo-app/tag_version.txt',
      ]
options:
  machineType: 'E2_HIGHCPU_8'
timeout: 3600s
